-- =============================================
-- BPM (電子簽核) 資料庫結構 (MS-SQL 2008)
-- =============================================

-- 員工資料表
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'BPM_EMPLOYEE' AND xtype = 'U')
BEGIN
    CREATE TABLE BPM_EMPLOYEE (
        EMP_NO VARCHAR(20) NOT NULL PRIMARY KEY,
        EMP_NAME NVARCHAR(100) NOT NULL,
        EMP_NAME_EN NVARCHAR(100) NULL,
        DEPT_CODE VARCHAR(20) NULL,
        DEPT_NAME NVARCHAR(100) NULL,
        POSITION NVARCHAR(100) NULL,
        EMAIL VARCHAR(255) NULL,
        PHONE VARCHAR(50) NULL,
        STATUS VARCHAR(10) NULL DEFAULT 'A',
        JOIN_DATE DATETIME NULL,
        LEAVE_DATE DATETIME NULL,
        MANAGER_EMP_NO VARCHAR(20) NULL,
        LAST_MODIFIED DATETIME NULL,
        SYNC_TIME DATETIME NOT NULL DEFAULT GETDATE()
    );

    CREATE INDEX IX_BPM_EMPLOYEE_DEPT ON BPM_EMPLOYEE(DEPT_CODE);
    CREATE INDEX IX_BPM_EMPLOYEE_STATUS ON BPM_EMPLOYEE(STATUS);
    CREATE INDEX IX_BPM_EMPLOYEE_SYNC ON BPM_EMPLOYEE(SYNC_TIME);
END
GO

-- 部門資料表
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'BPM_DEPARTMENT' AND xtype = 'U')
BEGIN
    CREATE TABLE BPM_DEPARTMENT (
        DEPT_CODE VARCHAR(20) NOT NULL PRIMARY KEY,
        DEPT_NAME NVARCHAR(100) NOT NULL,
        DEPT_NAME_EN NVARCHAR(100) NULL,
        PARENT_DEPT_CODE VARCHAR(20) NULL,
        DEPT_LEVEL VARCHAR(10) NULL,
        MANAGER_EMP_NO VARCHAR(20) NULL,
        STATUS VARCHAR(10) NULL DEFAULT 'A',
        LAST_MODIFIED DATETIME NULL,
        SYNC_TIME DATETIME NOT NULL DEFAULT GETDATE()
    );

    CREATE INDEX IX_BPM_DEPT_PARENT ON BPM_DEPARTMENT(PARENT_DEPT_CODE);
    CREATE INDEX IX_BPM_DEPT_STATUS ON BPM_DEPARTMENT(STATUS);
    CREATE INDEX IX_BPM_DEPT_SYNC ON BPM_DEPARTMENT(SYNC_TIME);
END
GO

-- 部門層級資料表
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'BPM_DEPT_HIERARCHY' AND xtype = 'U')
BEGIN
    CREATE TABLE BPM_DEPT_HIERARCHY (
        DEPT_CODE VARCHAR(20) NOT NULL,
        PARENT_DEPT_CODE VARCHAR(20) NOT NULL,
        LEVEL INT NOT NULL,
        PATH NVARCHAR(500) NOT NULL,
        SYNC_TIME DATETIME NOT NULL DEFAULT GETDATE(),
        PRIMARY KEY (DEPT_CODE, PARENT_DEPT_CODE)
    );

    CREATE INDEX IX_BPM_HIERARCHY_PARENT ON BPM_DEPT_HIERARCHY(PARENT_DEPT_CODE);
    CREATE INDEX IX_BPM_HIERARCHY_LEVEL ON BPM_DEPT_HIERARCHY(LEVEL);
END
GO
