-- =============================================
-- ERP 資料庫結構 (Oracle 11g)
-- =============================================

-- 員工資料表
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE ERP_EMPLOYEE (
        EMP_NO VARCHAR2(20) PRIMARY KEY,
        EMP_NAME NVARCHAR2(100) NOT NULL,
        EMP_NAME_EN NVARCHAR2(100) NULL,
        DEPT_CODE VARCHAR2(20) NULL,
        DEPT_NAME NVARCHAR2(100) NULL,
        POSITION NVARCHAR2(100) NULL,
        EMAIL VARCHAR2(255) NULL,
        PHONE VARCHAR2(50) NULL,
        STATUS VARCHAR2(10) DEFAULT ''A'',
        JOIN_DATE DATE NULL,
        LEAVE_DATE DATE NULL,
        MANAGER_EMP_NO VARCHAR2(20) NULL,
        LAST_MODIFIED DATE NULL,
        SYNC_TIME DATE DEFAULT SYSDATE NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- Table already exists
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_EMP_DEPT ON ERP_EMPLOYEE(DEPT_CODE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- Index already exists
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_EMP_STATUS ON ERP_EMPLOYEE(STATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_EMP_SYNC ON ERP_EMPLOYEE(SYNC_TIME)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 部門資料表
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE ERP_DEPARTMENT (
        DEPT_CODE VARCHAR2(20) PRIMARY KEY,
        DEPT_NAME NVARCHAR2(100) NOT NULL,
        DEPT_NAME_EN NVARCHAR2(100) NULL,
        PARENT_DEPT_CODE VARCHAR2(20) NULL,
        DEPT_LEVEL VARCHAR2(10) NULL,
        MANAGER_EMP_NO VARCHAR2(20) NULL,
        STATUS VARCHAR2(10) DEFAULT ''A'',
        LAST_MODIFIED DATE NULL,
        SYNC_TIME DATE DEFAULT SYSDATE NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_DEPT_PARENT ON ERP_DEPARTMENT(PARENT_DEPT_CODE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_DEPT_STATUS ON ERP_DEPARTMENT(STATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_DEPT_SYNC ON ERP_DEPARTMENT(SYNC_TIME)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 部門層級資料表
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE ERP_DEPT_HIERARCHY (
        DEPT_CODE VARCHAR2(20) NOT NULL,
        PARENT_DEPT_CODE VARCHAR2(20) NOT NULL,
        LEVEL NUMBER NOT NULL,
        PATH NVARCHAR2(500) NOT NULL,
        SYNC_TIME DATE DEFAULT SYSDATE NOT NULL,
        PRIMARY KEY (DEPT_CODE, PARENT_DEPT_CODE)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_HIERARCHY_PARENT ON ERP_DEPT_HIERARCHY(PARENT_DEPT_CODE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ERP_HIERARCHY_LEVEL ON ERP_DEPT_HIERARCHY(LEVEL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
